### ISSUE TITLE
Use Object.hasOwnProperty

### ISSUE THREAD

**Issue by tmcw** [inspect-js/is-core-module#16]
I noticed that this module is dependent on the `hasown` module. Node has had `Object.hasOwnProperty` since 0.10.0 - could this use the built-in method to slim its contribute to node_modules? I'd be happy to provide a PR if that helps.

**Comment by ljharb** [comment]
Technically it’s Object.prototype.hasOwnProperty.call, and that relies on both Object.prototype and Function.prototype being unmodified.

Using hasown ensures that later mutation of builtins doesn’t break things, so it’ll be relevant and necessary and beneficial forever.
